#!/bin/bash

ScriptPath=`unset CDPATH && cd "$(dirname ${BASH_SOURCE[0]})" >/dev/null && pwd`
BookmarkJSON="${ScriptPath}/bookmark.json"

_oo_bm_foreach() {
	local root=$(jq -r .root ${BookmarkJSON})
	filter=${1}
	shift 1
	while IFS= read -r line_obj; do
		eval "$(echo ${line_obj} | jq -r '.|@text "
			local NAME=\(.name)
			local PREFIX=\(.prefix)
			local CONDITION='"'"'\(.condition // "true")'"'"'
			local DEFAULT=\(.default // "")
		"' -)"
		PREFIX=$(eval "echo ${root}${PREFIX}")

		local current_dir=$(pwd | sed "s,^${PREFIX},,")
		declare ${NAME}="${current_dir%%/*}"
		declare ${NAME}="${!NAME:=${DEFAULT}}"
		export "${NAME}"

		! eval ${CONDITION} || "$@" || return
	done < <(jq -rc "${filter}" ${BookmarkJSON})
}

_oo_bm_foreach_exported_tags() {
	_oo_bm_foreach '.exported_tags[]' "$@"
}

_oo_bm_foreach_tags() {
	_oo_bm_foreach '.exported_tags[], .hidden_tags[]' "$@"
}

_oo_bm_enum_tag() {
	/bin/ls -Ad ${PREFIX}*/ 2>/dev/null | sed "s,^${PREFIX},," | sed "s,/$,,"
}

_oo_bm_enum_bookmarks() {
	while IFS= read -r line_obj; do
		eval "$(echo ${line_obj} | jq -r '.|@text "
			local CONDITION='"'"'\(.condition // "true")'"'"'
			local ITEMS=\"\(.items|keys|join(" "))\"
		"' -)"
		! eval ${CONDITION} || echo -n ${ITEMS} " "
	done < <(jq -rc '.bookmarks[]' ${BookmarkJSON})
}

_oo_bm_enum_bookmarks_wrt_exported_tags() {
	eval "$(_oo_bm_foreach_exported_tags 'eval' 'echo "local ${NAME}=\"${!NAME}\""')"
	_oo_bm_enum_bookmarks
}

_oo_bm_foreach_bookmarks() {
	local root=$(jq -r .root ${BookmarkJSON})
	while IFS= read -r line_obj; do
		eval "$(echo ${line_obj} | jq -r '.|@text "
			local PREFIX=\(.prefix)
			local CONDITION='"'"'\(.condition // "true")'"'"'
			local ITEMS='"'"'\(.items)'"'"'
		"' -)"
		PREFIX=$(eval "echo ${root}${PREFIX}")

		! eval ${CONDITION} || "$@" || return
	done < <(jq -rc ".bookmarks[]" ${BookmarkJSON})
}

