#!/bin/bash

__sub_confs() {
	cat <<EOF
status
binding
misc
plugins
_post
EOF
}

if [ "-l" = "$1" ]; then
	__sub_confs | sed -e 's/$/.tmux/'
	exit 0
fi

for conf in `__sub_confs`; do
	cat ${conf}.tmux
done
