#!/bin/bash
ScriptPath=`dirname $(readlink -f $0)`

_show_help() {
	cat >&2 << EOF
USAGE: backup [-h] [-f backup_list] <output_directory>
OPTIONS
	-h	show this message
	-f	specify the file listing all those should be backup.
ARGUMENTS
	specify the directory to store backup files. default to be /tmp/.config_backup
EOF
}

BKP_FILE_LIST=

OPTIND= OPTARG= opt=
while getopts "hf:" opt; do
	case $opt in
	f)	BKP_FILE_LIST=$OPTARG
		;;
	h)	_show_help; exit
		;;
	?)	_show_help; exit 1
		;;
	esac
done

shift $((OPTIND-1))

if [ 1 -gt $# ]; then
	echo "[Error] global: One argument is required to specify the position of backup files!!"
	exit 1
fi

if [ -z "$BKP_FILE_LIST" ]; then
	echo "[Notice] global: specify a list to backup"
	exit 0
fi

if [ ! -f "$BKP_FILE_LIST" ]; then
	echo "[Error] global: specified file unavailable!!" >&2
	exit 1
fi

BKP_DIR=${1:-/tmp/.config_backup}
mkdir -p "$BKP_DIR"

for f in `cat $BKP_FILE_LIST`; do
	if [ -e "$f" -a ! -e $BKP_DIR/$f ]; then
		install -d -m 755 -D $BKP_DIR/${f%/*}
		mv -v $f $BKP_DIR/$f
	fi
done

