#!/bin/bash

BKP_LIST=
INC_FILES=

OPTIND= OPTARG= opt=
while getopts "o:i:" opt; do
	case $opt in
	o)	BKP_LIST=$OPTARG
		;;
	i)	INC_FILES=$OPTARG
		;;
	esac
done

shift $((OPTIND-1))

BKP_LIST_TMP=`mktemp ${BKP_LIST}-XXXX.tmp`

while [ 0 -lt $# ]; do
	cat $1 >> $BKP_LIST_TMP
	shift
done

for file in $INC_FILES; do
	echo $file >> $BKP_LIST_TMP
done

cat $BKP_LIST_TMP | sort -u > $BKP_LIST
rm -f $BKP_LIST_TMP
