#!/bin/bash

BKP_LIST=
EXT_ROOT=

OPTIND= OPTARG= opt=
while getopts "o:r:" opt; do
	case $opt in
	o)	BKP_LIST=$OPTARG
		;;
	r)	EXT_ROOT=$OPTARG
		;;
	esac
done

shift $((OPTIND-1))

BKP_LIST_TMP=`mktemp ${BKP_LIST}-XXXX.tmp`

while [ 0 -lt $# ]; do
	cat $1 >> $BKP_LIST_TMP
	shift
done

for file in `cd $EXT_ROOT; find . -type f -o -type l`; do
	echo ${file#.} >> $BKP_LIST_TMP
done

cat $BKP_LIST_TMP | sort -u > $BKP_LIST
rm -f $BKP_LIST_TMP
