#!/bin/bash

if [ "Darwin" = "`uname -s`" ]; then
	Tar=/usr/local/bin/gtar
else
	Tar=/bin/tar
fi

SRC="$1" DST="$2"

if [ -e $DST -a ! -d $DST ]; then
	exit 1
fi

install -d -m 755 $DST
$Tar -C "$SRC" -cf - -- . | $Tar -C "$DST" --no-overwrite-dir -xvf -
